Repository gogf/gf, pull requests merged in 2022-12, with the labels that each got.

#2346 fix issue in gdb_core_utility.HasField caused by initialized position 1 for package clickhouse
  contrib/drivers/clickhouse/clickhouse.go
  contrib/drivers/clickhouse/clickhouse_test.go
Labels: awesome

#2335 fix: ghttp server static path config
  net/ghttp/ghttp_server_config_static.go
  net/ghttp/ghttp_server_handler.go
Labels: need more details

#2247 move TX from struct to interface for package gdb
  cmd/gf/internal/consts/consts_gen_dao_template_dao.go
  contrib/drivers/clickhouse/clickhouse.go
  contrib/drivers/clickhouse/clickhouse_test.go
  contrib/drivers/mysql/mysql_feature_scanlist_test.go
  contrib/drivers/mysql/mysql_model_test.go
  contrib/drivers/mysql/mysql_transaction_test.go
  contrib/drivers/sqlite/sqlite_model_test.go
  database/gdb/gdb.go
  database/gdb/gdb_core_transaction.go
  database/gdb/gdb_core_underlying.go
  database/gdb/gdb_core_utility.go
  database/gdb/gdb_model.go
  database/gdb/gdb_model_transaction.go
  database/gdb/gdb_model_utility.go
  database/gdb/gdb_z_example_test.go
Labels: awesome

#2308 fix BuildParams with urlEncode when len(v) <= 6
  internal/httputil/httputils.go
  net/ghttp/ghttp_z_unit_test.go
Labels: awesome

#2375 fix Unknown setting charset for clickhouse driver
  contrib/drivers/clickhouse/clickhouse.go
Labels: bug
