Repository gogf/gf, pull requests merged in 2024-10, with the labels that each got.

#3847 feat(trace): add trace for Custom trace client and provider
  contrib/trace/otlpgrpc/go.mod
  contrib/trace/otlpgrpc/otlpgrpc.go
  contrib/trace/otlphttp/go.mod
  contrib/trace/otlphttp/go.sum
  contrib/trace/otlphttp/otlphttp.go
  example/go.mod
  example/go.sum
  example/trace/README.MD
  example/trace/provider/grpc/main.go
  example/trace/provider/http/main.go
  example/trace/provider/internal/consts.go
  example/trace/provider/internal/provider.go
  example/trace/provider/internal/request.go
Labels: enhancement, discuss

#3822 fix(util/gconv): one parameter to same tag in multiple struct attributes mapping failed
  util/gconv/gconv_z_unit_issue_test.go
  util/gconv/internal/structcache/structcache_cached_struct_info.go
Labels: awesome

#3854 feat(database/gdb): add Exist support for checking records existance for certain condition
  contrib/drivers/clickhouse/clickhouse_z_unit_model_test.go
  contrib/drivers/mssql/mssql_z_unit_model_test.go
  contrib/drivers/mysql/mysql_z_unit_model_test.go
  contrib/drivers/oracle/oracle_z_unit_model_test.go
  contrib/drivers/pgsql/pgsql_z_unit_model_test.go
  contrib/drivers/sqlite/sqlite_z_unit_model_test.go
  contrib/drivers/sqlitecgo/sqlitecgo_z_unit_model_test.go
  database/gdb/gdb_model_select.go
Labels: feature, discuss
